[obs]
image=registry.opensuse.org/opensuse/distrobox-packaging:latest
pull=true
root=true
volume=/var/tmp:/var/tmp

pre_init_hooks=sed -i '/^baseurl=/ { /?REGION=EU/! s/$/?REGION=EU/ }' /etc/zypp/repos.d/*

# OBS stuff
additional_packages="obs-service-download_url obs-service-verify_file"

# Misc
additional_packages="neovim"
