[siga-tw]
image=registry.opensuse.org/opensuse/distrobox:latest
pull=true
init=false
start_now=true

#### PRE-INIT HOOKS

init_hooks=systemd-tmpfiles --create || true

#### PACKAGES

additional_packages="openSUSE-repos-Tumbleweed"

# Essentials
additional_packages="git neovim tmux lf htop fish"

# Misc
additional_packages="jq ripgrep"
additional_packages="awk file"

# Dev
additional_packages="clang gcc-c++ libc++-devel llvm"
additional_packages="cmake ninja"
additional_packages="boost-devel fmt-devel"
additional_packages="rustup"
additional_packages="python313-pyright nodejs"
additional_packages="gdb lldb"
additional_packages="lua-language-server"

# Misc
additional_packages="yt-dlp speedtest-cli"
additional_packages="terminfo-ghostty"

#### IMPORTS
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/distrobox
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/flatpak
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/podman
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/xdg-open
