[siga-arch]
image=quay.io/toolbx/arch-toolbox:latest
pull=true

#### PACKAGES

# Essentials
additional_packages="git neovim tmux lf htop fish wl-clipboard"

# Misc
additional_packages="jq ripgrep"
additional_packages="awk file"

# Dev
additional_packages="clang gcc libc++ llvm"
additional_packages="cmake ninja"
additional_packages="boost fmt"
additional_packages="rustup"
additional_packages="pyright nodejs"
additional_packages="gdb lldb"
additional_packages="lua-language-server"

# Misc
additional_packages="yt-dlp speedtest-cli"

#### EXPORTS
exported_bins="/usr/bin/git /usr/bin/nvim /usr/bin/lf /usr/bin/htop /usr/bin/fish"

#### IMPORTS
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/distrobox
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/flatpak
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/podman
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/xdg-open
